### ISSUE TITLE
Create 5 User stories for Persona 2: David

### ISSUE THREAD

**Issue by Noah-Giustini** [kaitlin31415/BCI4KidsMediapipe#29]
See issue #26 for Mural link

**Comment by RoxanneDuchesne** [comment]
User: David 

User Value: As a father of a daughter who uses Insight to communicate yes and no answers through moving her eyes I want to be able to recalibrate the app when it identifies a yes or no incorrectly so the system does not become frustrating for my daughter. 

User Story: David notices that the app displays yes when his daughter isn't communicating yes with her eyes. He clicks the recalibrate button at the top of the screen and is brought to the recalibration page. On that page, he can review the instructions for how to take training videos and upload them to the app. After taking new training videos he uploads them to the app. The app tells David to wait while the videos are processed. After processing the new videos the app confirms that the videos were successfully processed.
