### ISSUE TITLE
Report Knowledge Areas

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#37]
Please enter your strengths for languages/frameworks in the comments to identify how best to do the project.

**Comment by Noah-Giustini** [comment]
C++, backend development

**Comment by Dylan-Wheeler** [comment]
Most familiar with: Java, Kotlin
Competent with: Python, Javascript (plus just general web development with CSS and HTML), C/C++
I'm also down to work on frontend stuff even if most of my experience is with backend

**Comment by PriyavartRajain** [comment]
Most comfortable with Java, C++
Good with Python
Design and markup using HTML, CSS and Javascript
UI/UX Design. 
Familiarity with front-end
