### ISSUE TITLE
Research How a website API is created

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#54]
Look into how to set up an API endpoint and document best practices for development in this story

**Comment by kaitlin31415** [comment]
Look at Swagger API as a start

**Comment by Noah-Giustini** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-a-web-server-in-node-js-with-the-http-module

**Comment by Noah-Giustini** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

**Comment by Noah-Giustini** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

**Comment by kaitlin31415** [comment]
Closing in favor of UDP socket design
