### ISSUE TITLE
Try out Setup Instructions

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#57]
Confirm and Validate steps in Repo Readme

**Comment by PriyavartRajain** [comment]
Getting the following errors: 
`ERROR: C:/users/rajai/mediapipe/bci4kidsmediapipe/mediapipe/framework/deps/BUILD:67:11: output 'mediapipe/framework/deps/_objs/clock/monotonic_clock.obj' was not created`

`ERROR: C:/users/rajai/mediapipe/bci4kidsmediapipe/mediapipe/framework/deps/BUILD:67:11: Compiling mediapipe/framework/deps/monotonic_clock.cc failed: not all outputs were created or valid
Target //mediapipe/insight/insight_mediapipe/face_mesh:face_mesh_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.`
