### ISSUE TITLE
Error running the code from the repository

### ISSUE THREAD

**Issue by PriyavartRajain** [kaitlin31415/BCI4KidsMediapipe#74]
Error details: 

`ERROR: C:/users/rajai/mediapipe/bci4kidsmediapipe/mediapipe/framework/deps/BUILD:67:11: output 'mediapipe/framework/deps/_objs/clock/monotonic_clock.obj' was not created`

`ERROR: C:/users/rajai/mediapipe/bci4kidsmediapipe/mediapipe/framework/deps/BUILD:67:11: Compiling mediapipe/framework/deps/monotonic_clock.cc failed: not all outputs were created or valid
Target //mediapipe/insight/insight_mediapipe/face_mesh:face_mesh_cpu failed to build`

**Comment by kaitlin31415** [comment]
Closing as Bazel Mediapipe is not being used so this can be closed.
