### ISSUE TITLE
Setup iris tracking into base project

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#90]
Take the example repository and copy the necessary code to get the iris tracking position CSV similar to the Face tracking flow in python

https://github.com/Rassibassi/mediapipeDemos

This can be completed in a notebook or script. Please indicate which one.

**Comment by RoxanneDuchesne** [comment]
> 

I will be doing this in script :)

**Comment by RoxanneDuchesne** [comment]
Actual Time Frame: 3
