### ISSUE TITLE
Finalize Third Pass on FIGMA

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#97]
Finish up FIGMA doc in preparation for meeting with Eli

**Comment by Dylan-Wheeler** [comment]
All important pages have been updated or redesigned to have new fonts and colours. many smaller design changes have also been made including friendlier error messages and more consistent design elements. Added mockups for tips when first loading the page as well as more settings that users can make use of if needed.
Some pages/versions of pages have not been directly updated as they can be easily derived from the previous UI pass and mainly just involve redundancies such as different response card permutations or screen sizes.
